### PR TITLE
Remove the target's ability to use items while being controlled

### PR DESCRIPTION
**Pull request by ghost**
Without this patch, users are able to use weapons from the /weapons command while they're being controlled. They're able to activate them at a higher rate than usual due to the drop event being cancelled and that somehow activating the weapon's payload.

https://user-images.githubusercontent.com/44676012/102723735-081c4c80-4302-11eb-8297-a7403806ac60.mp4

### CODE REVIEW

**Comment by QuadraticKid** [comment]
there is a command called `/clear`

**Comment by ghost** [comment]
> there is a command called `/clear`

there is also a thing called saving and loading slots, so /clear doesn't exactly fix this issue

**Review by veast-mUJ9bDjOlP — APPROVED** [review]
kfc

**Comment by ghost** [comment]
@mathiascode

**Comment by mathiascode** [comment]
I can't reproduce this on Paper 1.16.4, which the server has just been upgraded to. Is this still an issue?

**Comment by ghost** [comment]
> I can't reproduce this on Paper 1.16.4, which the server has just been upgraded to. Is this still an issue?

That'll be because Weapons doesn't work on Paper 1.16.4, or at least on the updated Kaboom.

https://user-images.githubusercontent.com/44676012/103874157-b973fe00-50c8-11eb-8788-cb558dd01b50.mp4

**Comment by mathiascode** [comment]
Thanks, fixed in https://github.com/kaboomserver/weapons/commit/5980216b781c91367b6d8786cf6800691348034a.

**Pull request closed without merging**
